export const ALL_INDIAN_STATES = [
  { name: 'Andhra Pradesh', gstCode: 37, shortCode: 'AD' },
  { name: 'Arunachal Pradesh', gstCode: 12, shortCode: 'AR' },
  { name: 'Assam', gstCode: 18, shortCode: 'AS' },
  { name: 'Bihar', gstCode: 10, shortCode: 'BR' },
  { name: 'Chattisgarh', gstCode: 22, shortCode: 'CG' },
  { name: 'Delhi', gstCode: 7, shortCode: 'DL' },
  { name: 'Goa', gstCode: 30, shortCode: 'GA' },
  { name: 'Gujarat', gstCode: 24, shortCode: 'GJ' },
  { name: 'Haryana', gstCode: 6, shortCode: 'HR' },
  { name: 'Himachal Pradesh', gstCode: 2, shortCode: 'HP' },
  { name: 'Jammu and Kashmir', gstCode: 1, shortCode: 'JK' },
  { name: 'Jharkhand', gstCode: 20, shortCode: 'JH' },
  { name: 'Karnataka', gstCode: 29, shortCode: 'KA' },
  { name: 'Kerala', gstCode: 32, shortCode: 'KL' },
  { name: 'Lakshadweep Islands', gstCode: 31, shortCode: 'LD' },
  { name: 'Madhya Pradesh', gstCode: 23, shortCode: 'MP' },
  { name: 'Maharashtra', gstCode: 27, shortCode: 'MH' },
  { name: 'Manipur', gstCode: 14, shortCode: 'MN' },
  { name: 'Meghalaya', gstCode: 17, shortCode: 'ML' },
  { name: 'Mizoram', gstCode: 15, shortCode: 'MZ' },
  { name: 'Nagaland', gstCode: 13, shortCode: 'NL' },
  { name: 'Odisha', gstCode: 21, shortCode: 'OD' },
  { name: 'Pondicherry', gstCode: 34, shortCode: 'PY' },
  { name: 'Punjab', gstCode: 3, shortCode: 'PB' },
  { name: 'Rajasthan', gstCode: 8, shortCode: 'RJ' },
  { name: 'Sikkim', gstCode: 11, shortCode: 'SK' },
  { name: 'Tamil Nadu', gstCode: 33, shortCode: 'TN' },
  { name: 'Telangana', gstCode: 36, shortCode: 'TS' },
  { name: 'Tripura', gstCode: 16, shortCode: 'TR' },
  { name: 'Uttar Pradesh', gstCode: 9, shortCode: 'UP' },
  { name: 'Uttarakhand', gstCode: 5, shortCode: 'UK' },
  { name: 'West Bengal', gstCode: 19, shortCode: 'WB' },
  { name: 'Andaman and Nicobar Islands', gstCode: 35, shortCode: 'AN' },
  { name: 'Chandigarh', gstCode: 4, shortCode: 'CH' },
  {
    name: 'Dadra & Nagar Haveli and Daman & Diu',
    gstCode: 26,
    shortCode: 'DD'
  },
  { name: 'Ladakh', gstCode: 38, shortCode: 'LA' },
  { name: 'Other Territory', gstCode: 97, shortCode: 'OT' }
] as const;
