export const COMMON_PERMISSIONS = (module: string) => ({
  CREATE: `CREATE-${module}`,
  UPDATE: `UPDATE-${module}`,
  READ: `READ-${module}`,
  DELETE: `DELETE-${module}`
});

export const MODULES_PERMISSIONS = {
  COMPANY: COMMON_PERMISSIONS('COMPANY'),
  PLAN: COMMON_PERMISSIONS('PLAN'),
  ACCOUNTS: COMMON_PERMISSIONS('ACCOUNTS'),
  USERS: COMMON_PERMISSIONS('USERS'),
  CUSTOMER: COMMON_PERMISSIONS('CUSTOMER'),
  SUPPLIER: COMMON_PERMISSIONS('SUPPLIER'),
  BANK_ACCOUNT: COMMON_PERMISSIONS('BANK_ACCOUNT'),
  CASH_ACCOUNT: COMMON_PERMISSIONS('CASH_ACCOUNT'),
  BRANCH: COMMON_PERMISSIONS('BRANCH'),
  EMPLOYEE: COMMON_PERMISSIONS('EMPLOYEE'),
  DEPARTMENT: COMMON_PERMISSIONS('DEPARTMENT'),
  CATEGORIES: COMMON_PERMISSIONS('CATEGORIES'),
  BRANDS: COMMON_PERMISSIONS('BRANDS'),
  ITEM_METADATA: COMMON_PERMISSIONS('ITEM_METADATA'),
  ITEMS: COMMON_PERMISSIONS('ITEMS'),
  PURCHASE: COMMON_PERMISSIONS('PURCHASE'),
  PURCHASE_RETURN: COMMON_PERMISSIONS('PURCHASE_RETURN'),
  SALES: COMMON_PERMISSIONS('SALES'),
  SALES_RETURN: COMMON_PERMISSIONS('SALES_RETURN'),
  STOCKS: COMMON_PERMISSIONS('STOCKS'),
  PAYMENTS: COMMON_PERMISSIONS('PAYMENTS'),
  RECIPTS: COMMON_PERMISSIONS('RECIPTS'),
  EXPENSES: COMMON_PERMISSIONS('EXPENSES'),
  EXTERNAL_SERVICE: {
    GST_VERIFICATION: 'GST_VERIFICATION-EXTERNAL_SERVICE'
  },
  REPORTS: {
    DASHBOARD: 'DASHBOARD-REPORTS',
    DAY_BOOK: 'DAY_BOOK-REPORTS',
    RECENT_ACTIVITY: 'RECENT_ACTIVITY-REPORTS'
  }
} as const;
export type TMODULES_PERMISSIONS = keyof typeof MODULES_PERMISSIONS;
export const MODULES_PERMISSIONS_ARRAY = Object.keys(MODULES_PERMISSIONS);

export const ADMIN_PERMISSIONS = {
  COMPANY: {
    CREATE: false,
    UPDATE: 'UPDATE-COMPANY',
    READ: 'READ-COMPANY',
    DELETE: false
  },
  PLAN: {
    CREATE: false,
    UPDATE: false,
    READ: false,
    DELETE: false
  },
  ACCOUNTS: COMMON_PERMISSIONS('ACCOUNTS'),
  USERS: COMMON_PERMISSIONS('USERS'),
  CUSTOMER: COMMON_PERMISSIONS('CUSTOMER'),
  SUPPLIER: COMMON_PERMISSIONS('SUPPLIER'),
  BANK_ACCOUNT: COMMON_PERMISSIONS('BANK_ACCOUNT'),
  CASH_ACCOUNT: COMMON_PERMISSIONS('CASH_ACCOUNT'),
  BRANCH: COMMON_PERMISSIONS('BRANCH'),
  EMPLOYEE: COMMON_PERMISSIONS('EMPLOYEE'),
  DEPARTMENT: COMMON_PERMISSIONS('DEPARTMENT'),
  CATEGORIES: COMMON_PERMISSIONS('CATEGORIES'),
  BRANDS: COMMON_PERMISSIONS('BRANDS'),
  ITEM_METADATA: COMMON_PERMISSIONS('ITEM_METADATA'),
  ITEMS: COMMON_PERMISSIONS('ITEMS'),
  PURCHASE: COMMON_PERMISSIONS('PURCHASE'),
  PURCHASE_RETURN: COMMON_PERMISSIONS('PURCHASE_RETURN'),
  SALES: COMMON_PERMISSIONS('SALES'),
  SALES_RETURN: COMMON_PERMISSIONS('SALES_RETURN'),
  STOCKS: COMMON_PERMISSIONS('STOCKS'),
  PAYMENTS: COMMON_PERMISSIONS('PAYMENTS'),
  RECIPTS: COMMON_PERMISSIONS('RECIPTS'),
  EXPENSES: COMMON_PERMISSIONS('EXPENSES'),
  EXTERNAL_SERVICE: {
    GST_VERIFICATION: 'GST_VERIFICATION-EXTERNAL_SERVICE'
  },
  REPORTS: {
    DASHBOARD: 'DASHBOARD-REPORTS',
    DAY_BOOK: 'DAY_BOOK-REPORTS',
    RECENT_ACTIVITY: 'RECENT_ACTIVITY-REPORTS'
  }
};

export const EMPLOYEE_PERMISSIONS = {
  COMPANY: {
    CREATE: false,
    UPDATE: 'UPDATE-COMPANY',
    READ: 'READ-COMPANY',
    DELETE: false
  },
  PLAN: {
    CREATE: false,
    UPDATE: false,
    READ: false,
    DELETE: false
  },
  ACCOUNTS: {
    CREATE: false,
    UPDATE: false,
    READ: 'READ-ACCOUNTS',
    DELETE: false
  },
  USERS: {
    CREATE: 'CREATE-USERS',
    UPDATE: 'UPDATE-USERS',
    READ: 'READ-USERS',
    DELETE: false
  },
  CUSTOMER: {
    CREATE: 'CREATE-CUSTOMER',
    UPDATE: 'UPDATE-CUSTOMER',
    READ: 'READ-CUSTOMER',
    DELETE: false
  },
  SUPPLIER: {
    CREATE: 'CREATE-SUPPLIER',
    UPDATE: 'UPDATE-SUPPLIER',
    READ: 'READ-SUPPLIER',
    DELETE: false
  },
  BANK_ACCOUNT: {
    CREATE: false,
    UPDATE: false,
    READ: 'READ-BANK_ACCOUNT',
    DELETE: false
  },
  CASH_ACCOUNT: {
    CREATE: false,
    UPDATE: false,
    READ: 'READ-CASH_ACCOUNT',
    DELETE: false
  },
  BRANCH: {
    CREATE: false,
    UPDATE: false,
    READ: 'READ-BRANCH',
    DELETE: false
  },
  EMPLOYEE: {
    CREATE: false,
    UPDATE: false,
    READ: 'READ-EMPLOYEE',
    DELETE: false
  },
  DEPARTMENT: {
    CREATE: false,
    UPDATE: false,
    READ: false,
    DELETE: false
  },
  CATEGORIES: {
    CREATE: false,
    UPDATE: false,
    READ: 'READ-CATEGORIES',
    DELETE: false
  },
  BRANDS: {
    CREATE: false,
    UPDATE: false,
    READ: 'READ-BRANDS',
    DELETE: false
  },
  ITEM_METADATA: {
    CREATE: false,
    UPDATE: false,
    READ: 'READ-ITEM_METADATA',
    DELETE: false
  },
  ITEMS: {
    CREATE: false,
    UPDATE: false,
    READ: 'READ-ITEMS',
    DELETE: false
  },
  PURCHASE: {
    CREATE: false,
    UPDATE: false,
    READ: false,
    DELETE: false
  },
  PURCHASE_RETURN: {
    CREATE: false,
    UPDATE: false,
    READ: false,
    DELETE: false
  },
  SALES: COMMON_PERMISSIONS('SALES'),
  SALES_RETURN: COMMON_PERMISSIONS('SALES_RETURN'),
  STOCKS: COMMON_PERMISSIONS('STOCKS'),
  PAYMENTS: COMMON_PERMISSIONS('PAYMENTS'),
  RECIPTS: COMMON_PERMISSIONS('RECIPTS'),
  EXPENSES: COMMON_PERMISSIONS('EXPENSES'),
  EXTERNAL_SERVICE: {
    GST_VERIFICATION: 'GST_VERIFICATION-EXTERNAL_SERVICE'
  },
  REPORTS: {
    DASHBOARD: 'DASHBOARD-REPORTS',
    DAY_BOOK: 'DAY_BOOK-REPORTS',
    RECENT_ACTIVITY: 'RECENT_ACTIVITY-REPORTS'
  }
};

export const CUSTOMER_PERMISSIONS = {
  COMPANY: {
    CREATE: false,
    UPDATE: false,
    READ: 'READ-COMPANY',
    DELETE: false
  },
  PLAN: {
    CREATE: false,
    UPDATE: false,
    READ: false,
    DELETE: false
  },
  ACCOUNTS: {
    CREATE: false,
    UPDATE: false,
    READ: 'READ-ACCOUNTS',
    DELETE: false
  },
  USERS: {
    CREATE: false,
    UPDATE: 'UPDATE-USERS',
    READ: 'READ-USERS',
    DELETE: false
  },
  CUSTOMER: {
    CREATE: false,
    UPDATE: 'UPDATE-CUSTOMER',
    READ: 'READ-CUSTOMER',
    DELETE: false
  },
  SUPPLIER: {
    CREATE: false,
    UPDATE: 'UPDATE-SUPPLIER',
    READ: 'READ-SUPPLIER',
    DELETE: false
  },
  BANK_ACCOUNT: {
    CREATE: false,
    UPDATE: false,
    READ: 'READ-BANK_ACCOUNT',
    DELETE: false
  },
  CASH_ACCOUNT: {
    CREATE: false,
    UPDATE: false,
    READ: 'READ-CASH_ACCOUNT',
    DELETE: false
  },
  BRANCH: {
    CREATE: false,
    UPDATE: false,
    READ: 'READ-BRANCH',
    DELETE: false
  },
  EMPLOYEE: {
    CREATE: false,
    UPDATE: false,
    READ: 'READ-EMPLOYEE',
    DELETE: false
  },
  DEPARTMENT: {
    CREATE: false,
    UPDATE: false,
    READ: false,
    DELETE: false
  },
  CATEGORIES: {
    CREATE: false,
    UPDATE: false,
    READ: 'READ-CATEGORIES',
    DELETE: false
  },
  BRANDS: {
    CREATE: false,
    UPDATE: false,
    READ: 'READ-BRANDS',
    DELETE: false
  },
  ITEM_METADATA: {
    CREATE: false,
    UPDATE: false,
    READ: 'READ-ITEM_METADATA',
    DELETE: false
  },
  ITEMS: {
    CREATE: false,
    UPDATE: false,
    READ: 'READ-ITEMS',
    DELETE: false
  },
  PURCHASE: {
    CREATE: false,
    UPDATE: false,
    READ: 'READ-PURCHASE',
    DELETE: false
  },
  PURCHASE_RETURN: {
    CREATE: false,
    UPDATE: false,
    READ: 'READ-PURCHASE_RETURN',
    DELETE: false
  },
  SALES: COMMON_PERMISSIONS('SALES'),
  SALES_RETURN: COMMON_PERMISSIONS('SALES_RETURN'),
  STOCKS: {
    CREATE: false,
    UPDATE: false,
    READ: 'READ-STOCKS',
    DELETE: false
  },
  PAYMENTS: COMMON_PERMISSIONS('PAYMENTS'),
  RECIPTS: COMMON_PERMISSIONS('RECIPTS'),
  EXPENSES: {
    CREATE: false,
    UPDATE: false,
    READ: 'READ-EXPENSES',
    DELETE: false
  },
  EXTERNAL_SERVICE: {
    GST_VERIFICATION: 'GST_VERIFICATION-EXTERNAL_SERVICE'
  },
  REPORTS: {
    DASHBOARD: false,
    DAY_BOOK: false,
    RECENT_ACTIVITY: false
  }
};

export const SUPPLIER_PERMISSIONS = {
  COMPANY: {
    CREATE: false,
    UPDATE: false,
    READ: 'READ-COMPANY',
    DELETE: false
  },
  PLAN: {
    CREATE: false,
    UPDATE: false,
    READ: false,
    DELETE: false
  },
  ACCOUNTS: {
    CREATE: false,
    UPDATE: false,
    READ: 'READ-ACCOUNTS',
    DELETE: false
  },
  USERS: {
    CREATE: false,
    UPDATE: 'UPDATE-USERS',
    READ: 'READ-USERS',
    DELETE: false
  },
  CUSTOMER: {
    CREATE: false,
    UPDATE: 'UPDATE-CUSTOMER',
    READ: 'READ-CUSTOMER',
    DELETE: false
  },
  SUPPLIER: {
    CREATE: false,
    UPDATE: 'UPDATE-SUPPLIER',
    READ: 'READ-SUPPLIER',
    DELETE: false
  },
  BANK_ACCOUNT: {
    CREATE: false,
    UPDATE: false,
    READ: 'READ-BANK_ACCOUNT',
    DELETE: false
  },
  CASH_ACCOUNT: {
    CREATE: false,
    UPDATE: false,
    READ: 'READ-CASH_ACCOUNT',
    DELETE: false
  },
  BRANCH: {
    CREATE: false,
    UPDATE: false,
    READ: 'READ-BRANCH',
    DELETE: false
  },
  EMPLOYEE: {
    CREATE: false,
    UPDATE: false,
    READ: 'READ-EMPLOYEE',
    DELETE: false
  },
  DEPARTMENT: {
    CREATE: false,
    UPDATE: false,
    READ: false,
    DELETE: false
  },
  CATEGORIES: {
    CREATE: false,
    UPDATE: false,
    READ: 'READ-CATEGORIES',
    DELETE: false
  },
  BRANDS: {
    CREATE: false,
    UPDATE: false,
    READ: 'READ-BRANDS',
    DELETE: false
  },
  ITEM_METADATA: {
    CREATE: false,
    UPDATE: false,
    READ: 'READ-ITEM_METADATA',
    DELETE: false
  },
  ITEMS: {
    CREATE: false,
    UPDATE: false,
    READ: 'READ-ITEMS',
    DELETE: false
  },
  PURCHASE: {
    CREATE: false,
    UPDATE: false,
    READ: 'READ-PURCHASE',
    DELETE: false
  },
  PURCHASE_RETURN: {
    CREATE: false,
    UPDATE: false,
    READ: 'READ-PURCHASE_RETURN',
    DELETE: false
  },
  SALES: COMMON_PERMISSIONS('SALES'),
  SALES_RETURN: COMMON_PERMISSIONS('SALES_RETURN'),
  STOCKS: {
    CREATE: false,
    UPDATE: false,
    READ: 'READ-STOCKS',
    DELETE: false
  },
  PAYMENTS: COMMON_PERMISSIONS('PAYMENTS'),
  RECIPTS: COMMON_PERMISSIONS('RECIPTS'),
  EXPENSES: {
    CREATE: false,
    UPDATE: false,
    READ: 'READ-EXPENSES',
    DELETE: false
  },
  EXTERNAL_SERVICE: {
    GST_VERIFICATION: 'GST_VERIFICATION-EXTERNAL_SERVICE'
  },
  REPORTS: {
    DASHBOARD: false,
    DAY_BOOK: false,
    RECENT_ACTIVITY: false
  }
};
